### PR TITLE
change OrdersList

### PR DESCRIPTION
**Pull request by serhiizalyvshyi**

### CODE REVIEW

**Comment by pavloshushkov** [comment]
@seggaz why we separate repositories for FE & BE?

**Comment by serhiizalyvshyi** [comment]
> @seggaz why we separate repositories for FE & BE?

 I thought it would be more convenient.

**Comment by pavloshushkov** [comment]
> > @seggaz why we separate repositories for FE & BE?
> 
> I thought it would be more convenient.

Ok

**Comment by pavloshushkov** [comment]
Screenshot 2023-07-03 at 23 10 52  
Do not forget that you need to put me in the reviewers and yourself in the assign

**Review by pavloshushkov — APPROVED** [review]
approve 

* squashe commits and merge

**Pull request merged**
